[tool.poetry]
name = "pleasant"
version = "0.1.0"
description = "Routines for post-processing and analyzing PLE experiment data"
authors = ["Kilian Unterguggenberger <kilian.unterguggenberger@hu-berlin.de>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.5"
scipy = "^1.9.3"
matplotlib = "^3.6.2"
pandas = "^1.5.2"
lmfit = "^1.1.0"


[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.5.0"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
