name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install nox==2023.4.22
      - run: pip install poetry==1.2.2
      - run: pip install nox_poetry==1.0.3
      - run: nox --python ${{ matrix.python-version }}